# Generated by Django 4.2.5 on 2023-09-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='store.product', verbose_name='Liked products'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_products',
            field=models.ManyToManyField(blank=True, related_name='reviewed_users', through='store.Review', to='store.product', verbose_name='Reviewed products'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['full_name'], name='accounts_us_full_na_88336b_idx'),
        ),
    ]
