# Generated by Django 4.2.5 on 2023-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_vacancy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active status'),
        ),
    ]
